version: '3'

services:
  nodejs:
    build:
      context: './'
      dockerfile: Dockerfile
    image: node:16.15-alpine
    container_name: server
    networks:
      - app-network
    env_file:
      - ./settings.env
    ports:
      - '8080:8080'

  database:
    image: 'postgres:14.2-alpine'
    container_name: postgres
    networks:
      - app-network
    ports:
      - '5432:5432'
    env_file:
      - ./settings.env

networks:
  app-network:
    driver: bridge
